"""add_subcategory

Revision ID: 5258f50c47da
Revises: 89f07f3c1818
Create Date: 2022-05-02 05:50:00.299702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5258f50c47da'
down_revision = '89f07f3c1818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('subcategory', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'subcategory')
    # ### end Alembic commands ###
